import { TwitterApi } from "twitter-api-v2";
import fetch from "node-fetch";
import dotenv from "dotenv";

dotenv.config();

// Technical Guardrails
const BOT_DISCLOSURE = "\n\n(Generated by mystyleKPOP AI)";
const X_HOURLY_LIMIT = 5;

// Simple in-memory rate limiter
let xPostCount: Record<string, { count: number, resetAt: number }> = {};

/**
 * Validates if a URL is publicly accessible
 */
async function isPubliclyAccessible(url) {
    try {
        const res = await fetch(url, { method: "HEAD" });
        return res.ok;
    } catch (err) {
        return false;
    }
}

/**
 * Core Bot Logic
 */
export async function postToSNS({ platforms, text, imageUrls }) {
    const safeText = text + BOT_DISCLOSURE;
    const results = {};

    // --- X (Twitter) ---
    if (platforms.includes("x")) {
        try {
            const client = new TwitterApi({
                appKey: process.env.X_API_KEY,
                appSecret: process.env.X_API_SECRET_KEY,
                accessToken: process.env.X_ACCESS_TOKEN,
                accessSecret: process.env.X_ACCESS_TOKEN_SECRET,
            });

            let mediaIds = [];
            if (imageUrls && Array.isArray(imageUrls)) {
                for (const url of imageUrls.slice(0, 4)) {
                    const response = await fetch(url);
                    const buffer = await response.arrayBuffer();
                    const mediaId = await client.v1.uploadMedia(Buffer.from(buffer), { mimeType: 'image/png' });
                    mediaIds.push(mediaId);
                }
            }

            const tweet = await client.readWrite.v2.tweet({
                text: safeText,
                ...(mediaIds.length > 0 ? { media: { media_ids: mediaIds } } : {}),
            });

            results.x = { success: true, id: tweet.data.id };
        } catch (err) {
            results.x = { success: false, error: err.message };
        }
    }

    // --- Instagram ---
    if (platforms.includes("instagram")) {
        try {
            const igAccountId = process.env.INSTAGRAM_BUSINESS_ACCOUNT_ID;
            const accessToken = process.env.INSTAGRAM_ACCESS_TOKEN;

            const isUrlSafe = await isPubliclyAccessible(imageUrls[0]);
            if (!isUrlSafe) throw new Error("Image URL not publicly accessible");

            const containerRes = await fetch(`https://graph.facebook.com/v19.0/${igAccountId}/media`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    image_url: imageUrls[0],
                    caption: safeText,
                    access_token: accessToken,
                }),
            });
            const containerData = await containerRes.json();

            const publishRes = await fetch(`https://graph.facebook.com/v19.0/${igAccountId}/media_publish`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ creation_id: containerData.id, access_token: accessToken }),
            });
            const publishData = await publishRes.json();

            results.instagram = { success: true, id: publishData.id };
        } catch (err) {
            results.instagram = { success: false, error: err.message };
        }
    }

    return results;
}
